### PR TITLE
Fix missing dangling comment in exports

### LINKED ISSUE #698: Unprinted comment after `export`
```js
export/* missing comment */{};
```

```
Error: Comment "missing comment" was not printed. Please report this error!
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22export%2F*%20missing%20comment%20*%2F%7B%7D%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

### PR DESCRIPTION
**Pull request by yamafaktory**
This should fix #698.

### CODE REVIEW

File: src/printer.js [hunk 1]
```diff
@@ -2025,6 +2025,8 @@ function printExportDeclaration(path, options, print) {
     parts.push("default ");
   }
 
+  parts.push(comments.printDanglingComments(path, options, true));
```
Comment (vjeux) [inline src/printer.js]: Please add `/* sameIndent */ true`

Comment (yamafaktory) [inline src/printer.js]: No problem 👍.
