### PR TITLE
Fix Flow union type annotations indentation

### LINKED ISSUE #646: "Algebraic types" in Flow don't look nice
I guess this isn't very common code, but these type definitions in Flow don't look too nice - the line bginning with mode: 'moving' should probably be indented further.

screen shot 2017-02-08 at 13 25 03

(v. 0.15.0)

### PR DESCRIPTION
**Pull request by yamafaktory**
This should fix #646 🤞.

### CODE REVIEW

**Comment by yamafaktory** [comment]
Ok... this needs a lot more reformatting regarding the tests.

**Comment by yamafaktory** [comment]
@vjeux + @houshuang Should be great to know if this is going in the right direction before I refactor all the tests accordingly!

Example:

```js
/* @flow */

type Tree<T> =
  | { type: "Node", value: T, left: Tree<T>, right: Tree<T> }
  | { type: "EmptyTree" }
  | {
  mode: 'moving',
  currentActivity: Activity
  }
  | { type: "Test"}
```

Turns into:

```js
/* @flow */

type Tree<T> =
  | { type: "Node", value: T, left: Tree<T>, right: Tree<T> }
  | { type: "EmptyTree" }
  | {
      mode: "moving",
      currentActivity: Activity
  }
  | { type: "Test" };
```

**Comment by houshuang** [comment]
Definitively better, but should the closing bracket be indented as far as the opening bracket?

```
/* @flow */

type Tree<T> =
  | { type: "Node", value: T, left: Tree<T>, right: Tree<T> }
  | { type: "EmptyTree" }
  | {
      mode: "moving",
      currentActivity: Activity
    }
  | { type: "Test" };
```

?

**Comment by yamafaktory** [comment]
@houshuang I agree with you, this would make it more readable. As it starts to involve an opinionated indentation, it should be great to have @jlongster's views on that!

**Comment by jlongster** [comment]
I think @houshuang, we should probably line up the closing brace as well. Thanks for this! I'll comment in the PR.

File: src/printer.js [hunk 1]
```diff
@@ -626,7 +628,7 @@ function genericPrintNoParens(path, options, print) {
           concat([
             leftBrace,
             indent(
-              options.tabWidth,
+              options.tabWidth * (parentIsUnionTypeAnnotation ? 2 : 1),
```
Comment (jlongster) [inline src/printer.js]: I think we need to calculate it differently. This is a special case where we are trying to line something up specifically. We want to indent it according to `| {`, which takes up 3 characters. So I think this should just be 

`options.tabWidth + (parentIsUnionTypeAnnotation ? 3 : 0)`

Because it doesn't matter if the tab width is 1 or 5; you always want to bump everything over 3 spaces because that's what you're trying to line up with.

Comment (jlongster) [inline src/printer.js]: To indent the end brace, just to a similar thing below around `rightBrace`:

`parentIsUnionTypeAnnotation ? indent(3, rightBrace), rightBrace`

I could be wrong, but something like that should work.

Comment (jlongster) [inline src/printer.js]: Actually, indentations are only applied when emitting newlines so you need to include the newline:

```js
indent(parentIsUnionTypeAnnotation ? 3 : 0,
       concat([options.bracketSpacing ? line : softline, rightBrace]))
```

Haven't actually testing this code

Comment (yamafaktory) [inline src/printer.js]: Awesome! I'll try it and fix the tests too! Yesterday evening I was trying to wrap my head around that indentation thing, playing with different values passed via the corresponding flag.

**Comment by yamafaktory** [comment]
@jlongster I've implemented it and updated the tests accordingly. The only thing I slightly changed was the indentation size for the closing right brace in order to keep it aligned.

File: src/printer.js [hunk 2]
```diff
@@ -628,15 +628,17 @@ function genericPrintNoParens(path, options, print) {
           concat([
             leftBrace,
             indent(
-              options.tabWidth * (parentIsUnionTypeAnnotation ? 2 : 1),
+              options.tabWidth + (parentIsUnionTypeAnnotation ? 3 : 0),
```
Comment (rhengles) [inline src/printer.js]: @jlongster @yamafaktory

I think this line should be indented 2 spaces:

`options.tabWidth + (parentIsUnionTypeAnnotation ? 2 : 0)`

Because when indenting a normal object, the opening brace is not counted.

```javascript
{
  key: "value",
}
```

So, from the characters `| {` only the pipe and the space should be counted.

Comment (yamafaktory) [inline src/printer.js]: @rhengles I agree with you. This is how I tried to make it work in the first place with a different calculation. What's your opinion on this @jlongster?

Comment (jlongster) [inline src/printer.js]: @yamafaktory That's a good point, yep I think we should do what @rhengles said (sorry for the slow reply)

**Comment by yamafaktory** [comment]
@jlongster this should be good to go now 👍

**Comment by vjeux** [comment]
Thank you!
