### PR TITLE
Fix comma when an arrow function with no arguments breaks

### LINKED ISSUE #118: Wrapping algorithm for callback arrow functions adds a comma to the arguments list
> Version: 0.0.5 (npm@latest); also 0.0.4, and prettier-browser.

Example: ([prettier-browser](https://vjeux.github.io/prettier-browser/#%7B%22content%22%3A%22func('a%20short%20name'%2C%20()%20%3D%3E%20%7B%5Cn%20%20return%20true%3B%5Cn%7D)%5Cn%5Cnfunc('a%20very%20very%20very%20very%20long%20long%20long%20name%20that%20exceeds%20the%20width%20limit'%2C%20()%20%3D%3E%20%7B%5Cn%20%20return%20true%3B%5Cn%7D)%5Cn%5Cnfunc('a%20very%20very%20very%20very%20long%20long%20long%20name%20that%20exceeds%20the%20width%20limit'%2C%20function()%20%7B%5Cn%20%20return%20true%3B%5Cn%7D)%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22useFlowParser%22%3Afalse%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3Atrue%2C%22bracketSpacing%22%3Atrue%7D%7D))

```js
func('a very very very very long long long name that exceeds the width limit', () => {
  return true;
})

// becomes 

func('a very very very very long long long name that exceeds the width limit', (
  ,
) => 
  {
    return true;
  });
```

Where did the comma in the arguments list come from?

It doesn't happen with shorter functions that _don't_ exceed the line length limit, nor with a `function` callback.

```js
// input
func('a short name', () => {
  return true;
})

// output
func('a short name', () => {
  return true;
});
```

```js
// input
func('a very very very very long long long name that exceeds the width limit', function() {
  return true;
})

// output
func(
  'a very very very very long long long name that exceeds the width limit',
  function() {
    return true;
  },
);
```

> Side-note: The output for the incorrect function causes `prettier` to throw an error: [prettier-browser](https://vjeux.github.io/prettier-browser/#%7B%22content%22%3A%22%5Cnfunc('a%20very%20very%20very%20very%20long%20long%20long%20name%20that%20exceeds%20the%20width%20limit'%2C%20(%5Cn%20%20%2C%5Cn)%20%3D%3E%20%5Cn%20%20%7B%5Cn%20%20%20%20return%20true%3B%5Cn%20%20%7D)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22useFlowParser%22%3Afalse%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3Atrue%2C%22bracketSpacing%22%3Atrue%7D%7D). Is the comma actually illegal there, or should I file that as a separate bug?

---

This looks like a wonderful tool. I'm really excited to see where it leads.

### PR DESCRIPTION
**Pull request by vjeux**
Fixes #118

### CODE REVIEW

File: src/printer.js [hunk 1]
```diff
@@ -1790,6 +1790,10 @@ function printFunctionParams(path, print, options) {
     printed.push(concat([ "...", path.call(print, "rest") ]));
   }
 
+  if (printed.length === 0) {
+    return "()";
+  }
+
   return concat([
     "(",
     indent(
```
Comment (vjeux) [inline src/printer.js]: I also tried adding `printed.length > 0 &&` next to `options.trailingComma`, which is the correct, fix but it doesn't look really good.

```js
veryLongCall(VERY_VERY_VERY_VERY_VERY_VERY_VERY_VERY_VERY_VERY_LONG_CONSTANT, (

) =>
  {});
```

Comment (jlongster) [inline src/printer.js]: Yep, this is the easiest thing to do! The representation below can't completely collapse in this case because it wants to break across lines. But because we can statically analyze this and easily know we never want to break up the parens your solution is correct.
