### PR TITLE
Hug elements inside of JSXExpressionContainer

### LINKED ISSUE #196: [JSX] Wrong indent for arrow functions inside of `{}`
```js
<Something>
  {() => (
      <SomethingElse>
        <span />
      </SomethingElse>
    )}
</Something>;
```

### LINKED ISSUE #197: [JSX] Single arrays and objects should stay on the same line and not put on the next indent
```js
<View
  style={
    [
      {
        someVeryLongStyle1: "true",
        someVeryLongStyle2: "true"
      }
    ]
  }
/>;
```

should be

```js
<View
  style={[
    {
      someVeryLongStyle1: "true",
      someVeryLongStyle2: "true"
    }
  ]}
/>;
```

and 

```js
<View
  style={
    {
      someVeryLongStyle1: "true",
      someVeryLongStyle2: "true"
    }
  }
/>;
```

should be

```js
<View
  style={{
    someVeryLongStyle1: "true",
    someVeryLongStyle2: "true"
  }}
/>;
```

### PR DESCRIPTION
**Pull request by vjeux**
Fixes #197
Fixes #196

### CODE REVIEW

File: src/printer.js [hunk 1]
```diff
@@ -1098,6 +1098,14 @@ function genericPrintNoParens(path, options, print) {
     case "JSXSpreadAttribute":
       return concat([ "{...", path.call(print, "argument"), "}" ]);
     case "JSXExpressionContainer":
+      const shouldIndent =
+        n.expression.type !== 'ArrayExpression' &&
+        n.expression.type !== 'ObjectExpression';
```
Comment (vjeux) [inline src/printer.js]: We'll probably want to add more things here over time

File: tests/jsx/__snapshots__/jsfmt.spec.js.snap [hunk 2]
```diff
@@ -1,3 +1,130 @@
...
+  {() => (
+    <SomethingElse>
+      <span />
+    </SomethingElse>
+  )}
+</Something>;
+
+<Something>
+  {items.map(
+    item => (
```
Comment (vjeux) [inline tests/jsx/__snapshots__/jsfmt.spec.js.snap]: this one will be fixed by #211

File: src/printer.js [hunk 3]
```diff
@@ -1098,6 +1098,17 @@ function genericPrintNoParens(path, options, print) {
...
+      const shouldIndent =
+        n.expression.type !== 'ArrayExpression' &&
+        n.expression.type !== 'ObjectExpression' &&
+        n.expression.type !== 'ArrowFunctionExpression' &&
+        n.expression.type !== 'CallExpression' &&
+        n.expression.type !== 'FunctionExpression';
+
+      if (!shouldIndent) {
+        return concat(["{", path.call(print, "expression"), "}"]);
+      }
```
Comment (jlongster) [inline src/printer.js]: I'm not sure I get what the `shouldIndent` logic is? Take this example:

```js
<Something>
  {() => (
      <SomethingElse>
        <span />
      </SomethingElse>
    )}
</Something>;
```

I thought that the indent below is the indentation for the opening `{` on the line 2. It's not clear to me why this bug is happening, but it's also getting late so I might not be thinking clearly... Thanks for fixing these JSX bugs, they've annoyed me as well!

I'd like to look at this again tomorrow before merging so I can understand what's happening.

**Comment by jlongster** [comment]
Sorry I haven't merged this yet. I will go through this again tomorrow (there's something I want to understand here). I'm finishing up some other work right now.

File: src/printer.js (hunk 3 above)
Comment (vjeux) [inline src/printer.js]: Yeah, I'm not really sure what's going on here and it would be nice to find out, instead of blindly sending a fix that happens to fix it.

**Comment by jlongster** [comment]
What's happening is the JSX code has hard lines, so it breaks across lines. The previous code assumed all code was on one line, and added indentation for itself when it breaks. This pattern doesn't work when the inner contents forces itself across lines because it'll inherit an extra indentation level. 

This bug will happen with anything that breaks itself up. For example, blocks have hard lines so we can repro with this:

```js
<Something>
  {() => {
      return 5;
    }}
</Something>;
```

If the inner contents may break themselves up, you need to use `multilineGroup`. I'll comment where the change that.

Otherwise, your PR looks good. It's a bit unrelated actually, just exposed this bug.

File: src/printer.js [hunk 4]
```diff
@@ -1098,6 +1098,17 @@ function genericPrintNoParens(path, options, print) {
...
+
       return group(
```
Comment (jlongster) [inline src/printer.js]: This needs to be a `multilineGroup`.

But this has me wondering: Should `JSXExpressionContainer` ever include lines and break the expression to next line?

File: src/printer.js (hunk 3 above)
Comment (jlongster) [inline src/printer.js]: This code is good. The comment below about the group will fix other bugs.

File: src/printer.js (hunk 4 above)
Comment (vjeux) [inline src/printer.js]: Great find, it also fixes a few more snapshots :)

File: tests/react/__snapshots__/jsfmt.spec.js.snap [hunk 5]
```diff
@@ -200,13 +200,13 @@ var Example = React.createClass({
 var ok_void = (
   <Example
     func={() => {
-      }}
```
Comment (vjeux) [inline tests/react/__snapshots__/jsfmt.spec.js.snap]: yay
