### PR TITLE
[WIP] Fix Flow DeclareTypeAlias

### LINKED ISSUE #659: Flow declarations lose their `declaration` keyword
prettier transforms a [Flow declaration](https://flowtype.org/docs/declarations.html) like

```js
declare type Foo = string;
```

into

```js
type Foo = string;
```

Here's [that in the web UI](https://jlongster.github.io/prettier/#%7B%22content%22%3A%22declare%20type%20Foo%20%3D%20string%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D).

Are flow declarations in scope for prettier or are they not considered proper JavaScript?

### PR DESCRIPTION
**Pull request by yamafaktory**
This is an experiment that aims to fix #659. The tests will fail as the `declare` keywords are missing (as Flow doesn't distinguish between `declare type foo` and `type foo`) and should be put back. What's your opinion on that @vjeux? Maybe I missed something in order to be able to read the source of a given node in the AST (source was null for the targeted one)?

### CODE REVIEW

File: src/printer.js [hunk 1]
```diff
@@ -1558,7 +1559,11 @@ function genericPrintNoParens(path, options, print) {
     case "DeclareTypeAlias":
     case "TypeAlias": {
       const parent = path.getParentNode(1);
-      if (parent && parent.type === "DeclareModule") {
+      if (
+        (parent && parent.type === "DeclareModule") ||
```
Comment (vjeux) [inline src/printer.js]: You don't need this anymore

File: src/doc-utils.js [hunk 2]
```diff
@@ -126,11 +126,19 @@ function propagateBreaks(doc) {
   );
 }
 
+function getNodeSource (node, text) {
+  return text
```
Comment (vjeux) [inline src/doc-utils.js]: In utils, there's `locStart` and `locEnd` you can use to get the proper position.

File: index.js [hunk 3]
```diff
@@ -51,7 +51,7 @@ function attachComments(text, ast, opts) {
 function format(text, opts) {
   const ast = parse(text, opts);
   attachComments(text, ast, opts);
-  const doc = printAstToDoc(ast, opts);
+  const doc = printAstToDoc(ast, opts, text);
```
Comment (vjeux) [inline index.js]: `options.originalText` contains the raw text, you don't need to thread it through there.

File: src/printer.js [hunk 4]
```diff
@@ -1558,7 +1559,11 @@ function genericPrintNoParens(path, options, print) {
...
+          n.type === "DeclareTypeAlias" ||
+          (options.parser === "flow" && /declare/.test(getNodeSource(n, text)))
```
Comment (vjeux) [inline src/printer.js]: Can you do `source.startsWith("declare")`, this way it's going to have less false positives if you happen to have named the type `declareSomething` or have written `declare` somewhere in the type declaration.

**Comment by vjeux** [comment]
In a follow up we'll also want do it for

```js
    case "DeclareInterface":
    case "InterfaceDeclaration": {
      const parent = path.getParentNode(1);
      if (parent && parent.type === "DeclareModule") {
        parts.push("declare ");
      }
```

File: src/printer.js (hunk 1 above)
Comment (yamafaktory) [inline src/printer.js]: I think we still need it in order to catch the following:

```js
declare module Foo3 {
  declare type Foo4 = string;
}
```

File: src/printer.js (hunk 4 above)
Comment (yamafaktory) [inline src/printer.js]: Cool, thanks!

File: src/doc-utils.js (hunk 2 above)
Comment (yamafaktory) [inline src/doc-utils.js]: Great but those helper functions are based on the node's range. In our case, the `declare` keyword is not counted in (I tried it):

```js
declare type Foo2 = string; // range: [ 8, 27 ]
```

File: src/printer.js (hunk 1 above)
Comment (yamafaktory) [inline src/printer.js]: Forget about it, you're right 👍.

File: src/doc-utils.js (hunk 2 above)
Comment (vjeux) [inline src/doc-utils.js]: Oh yeah you are right, I was looking at babylon parser which contains it. Sorry

File: src/doc-utils.js [hunk 5]
```diff
@@ -126,11 +126,19 @@ function propagateBreaks(doc) {
   );
 }
 
+function getNodeSource (node, text) {
```
Comment (vjeux) [inline src/doc-utils.js]: We don't want to make this a generic function, especially given that it is giving the entire line and not the actual range.

File: src/printer.js [hunk 6]
```diff
@@ -1557,8 +1558,11 @@ function genericPrintNoParens(path, options, print) {
       return "string";
     case "DeclareTypeAlias":
     case "TypeAlias": {
-      const parent = path.getParentNode(1);
-      if (parent && parent.type === "DeclareModule") {
+      const nodeSource = getNodeSource(n, options.originalText)
```
Comment (vjeux) [inline src/printer.js]: this function is super expensive as it does a copy of the entire file in an array line by line. Instead you could do

```js
options.originalText.slice(0, locStart(n)).match(/declare\s*$/)
```

**Comment by yamafaktory** [comment]
@vjeux should be better now, thanks for your guidance! The only thing I need to fix is the dropped line in the failing test (I added this new test initially, current master implementation also drop the line...).

File: src/printer.js [hunk 7]
```diff
@@ -1442,8 +1442,11 @@ function genericPrintNoParens(path, options, print) {
       ]);
     case "DeclareInterface":
     case "InterfaceDeclaration": {
-      const parent = path.getParentNode(1);
-      if (parent && parent.type === "DeclareModule") {
+      const nodeSource = options.originalText.slice(0, util.locStart(n));
+      if (
+        n.type === "DeclareInterface" ||
+          (options.parser === "flow" && nodeSource.match(/declare\s*$/))
```
Comment (vjeux) [inline src/printer.js]: Okay, last small thing and should be good to go, would be nice to put the flow detection code a function, so we don't have to copy and paste this crazy logic twice.

Also, it means we don't do the slice in case we are in babylon.

File: tests/flow/tagged-unions/__snapshots__/jsfmt.spec.js.snap [hunk 8]
```diff
@@ -95,20 +95,20 @@ if (data.kind === \"user\") {
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 /* @flow */
 
-interface IDataBase {
+declare interface IDataBase {
```
Comment (vjeux) [inline tests/flow/tagged-unions/__snapshots__/jsfmt.spec.js.snap]: Tay!

File: src/printer.js (hunk 7 above)
Comment (yamafaktory) [inline src/printer.js]: Ok, will do it 👍

File: tests/flow/tagged-unions/__snapshots__/jsfmt.spec.js.snap (hunk 8 above)
Comment (yamafaktory) [inline tests/flow/tagged-unions/__snapshots__/jsfmt.spec.js.snap]: What's wrong there? Shouldn't it be like that?

File: src/printer.js (hunk 7 above)
Comment (yamafaktory) [inline src/printer.js]: Do you want to compute the regex on the fly (with `new RegExp`) too so that the matching word could be anything else than `declare`?

File: tests/flow/tagged-unions/__snapshots__/jsfmt.spec.js.snap (hunk 8 above)
Comment (vjeux) [inline tests/flow/tagged-unions/__snapshots__/jsfmt.spec.js.snap]: Sorry, I meant Yay! It's great that we now preserve what the developer entered

Comment (vjeux) [inline tests/flow/tagged-unions/__snapshots__/jsfmt.spec.js.snap]: Sorry, I meant Yay! It's great that we now preserve what the developer entered

File: src/printer.js (hunk 7 above)
Comment (yamafaktory) [inline src/printer.js]: i.e.:

```js
function isFlowNodeStartWith(node, keyword) {
  const startWithRegex = new Regex("/" + keyword + "\s*$/")
  const nodeSource = options.originalText.slice(0, util.locStart(n));
  return (options.parser === "flow" && nodeSource.match(startWithRegex))
}
```

Comment (vjeux) [inline src/printer.js]: No, declare is the only thing that we have issues with. It there are more in the future we may want to generalize but that's unlikely.

File: src/printer.js [hunk 9]
```diff
@@ -2764,6 +2768,11 @@ function shouldPrintSameLine(node) {
     type === "UnaryExpression";
 }
 
+function isFlowNodeStartingWithDeclare(node, options) {
+  const nodeSource = options.originalText.slice(0, util.locStart(node));
```
Comment (vjeux) [inline src/printer.js]: Okay, last thing I promise :p

Would be nice to return early if the parser is not flow. This way we don't need to compute the slice.

```js
if (option.parser !== "flow") {
  return false;
}

return options.originalText
  .slice(0, util.locStart(node))
  .match(/declare\s*$/);
```

Comment (yamafaktory) [inline src/printer.js]: Absolutely no problem!

**Comment by yamafaktory** [comment]
@vjeux last thing: this one (addition) is still going to fail https://github.com/yamafaktory/prettier/blob/659-declare-type-alias/tests/flow/declare_type/lib/__snapshots__/jsfmt.spec.js.snap#L11. The empty line is somehow skipped (and as I mentioned it before, this is actually a bug present in master).

**Comment by vjeux** [comment]
<3

Can you look at Travis and why it's failing?

**Comment by yamafaktory** [comment]
@vjeux please see https://github.com/jlongster/prettier/pull/669#issuecomment-279247348.

**Comment by yamafaktory** [comment]
I don't know why this line is skipped... Shouldn't it be handled directly?

**Comment by yamafaktory** [comment]
@vjeux If I play with the following code:

```js
declare module ModuleAliasFoo {
  declare type baz = number;
  declare type toz = string;
  declare function foo(bar: baz): toz;
}

const b = 5;
```

This will be fine with Babylon but not Flow (empty line dropped).

To go deeper, if I try to print the body of the parent node, this is what I get:

```js
// Babylon
[ Node {
    type: 'DeclareModule',
    start: 0,
    end: 130,
    loc: SourceLocation { start: [Object], end: [Object] },
    id: 
     Node {
       type: 'Identifier',
       start: 15,
       end: 29,
       loc: [Object],
       name: 'ModuleAliasFoo' },
    body: 
     Node {
       type: 'BlockStatement',
       start: 30,
       end: 130,
       loc: [Object],
       body: [Object] } },
  Node {
    type: 'VariableDeclaration',
    start: 132,
    end: 144,
    loc: SourceLocation { start: [Object], end: [Object] },
    declarations: [ [Object] ],
    kind: 'const' } ]
```

```js
// Flow
[ { type: 'DeclareModule',
    loc: { source: null, start: [Object], end: [Object] },
    range: [ 0, 137 ],
    id: 
     { type: 'Identifier',
       loc: [Object],
       range: [Object],
       name: 'ModuleAliasFoo',
       typeAnnotation: null,
       optional: false },
    body: 
     { type: 'BlockStatement',
       loc: [Object],
       range: [Object],
       body: [Object] },
    kind: 'CommonJS' },
  { type: 'VariableDeclaration',
    loc: { source: null, start: [Object], end: [Object] },
    range: [ 132, 144 ],
    declarations: [ [Object] ],
    kind: 'const' } ]
```

And here comes the weird thing: for Flow, there is an overlap in the ranges of the nodes ([0, 137] - [132, 144]). I guess this is the reason for the dropped line. I didn't find anything related to that in the Flow issue tracker.

**Comment by vjeux** [comment]
In order to know if we should maintain the line, we skip characters at the beginning/end of the line from the start/end of the node. because declare is outside of the node in Flow, we need to "fix" the node location.

You can add things here: https://github.com/jlongster/prettier/blob/6632b95497423ed07ddaee8035abed99aaf5a777/src/util.js#L21

However, could you just re-record the tests here with the issue so that we can ship this and then do that work on another pull request?

**Comment by yamafaktory** [comment]
@vjeux Thanks for the guidance, didn't know about that 👍. I've updated the tests as requested, this should be good to go now!

**Comment by yamafaktory** [comment]
It looks like the tests for Node v4 are hanging forever...

**Comment by vjeux** [comment]
Yay, thanks for keeping up with my comments, so glad it is fixed!
