### PR TITLE
Fix use strict as expression statement

### LINKED ISSUE #536: Changes ExpressionStatement into Directive
Input:

```js
("use strict")
```

Output:

```js
"use strict";
```

... which has changed the meaning of the code.

Expected:

```js
("use strict");
```

Found by reading [shift-codegen-js' source code](https://github.com/shapesecurity/shift-codegen-js/blob/8a9c8c1a72dd43044379bcd64003937caaa1678d/src/formatted-codegen.js#L1143-L1148)

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22(%5C%22use%20strict%5C%22)%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

### PR DESCRIPTION
**Pull request by yamafaktory**
Should fix #536.

### CODE REVIEW

**Comment by yamafaktory** [comment]
Seems like my test is wrong somehow: `Error: No message was provided`... @vjeux / @jlongster how can I fix that, I couldn't find anything related to that for Jest?

File: tests/expression_statement/use_strict.js [hunk 1]
```diff
@@ -0,0 +1,2 @@
+// Parentheses around expression statement should be preserved in this case.
+("use strict");
```
Comment (vjeux) [inline tests/expression_statement/use_strict.js]: Can you also add a test for

```js
"use strict";
```

to make sure we don't regress

File: tests/expression_statement/jsfmt.spec.js [hunk 2]
```diff
@@ -0,0 +1 @@
+run_spec(__dirname);
```
Comment (vjeux) [inline tests/expression_statement/jsfmt.spec.js]: can you also add

```js
run_spec(__dirname, {parser: 'babylon'});
```

the two parsers handle directives differently.

File: tests/expression_statement/use_strict.js [hunk 3]
```diff
@@ -0,0 +1,4 @@
...
+// Ensure no regression.
+"use strict";
```
Comment (vjeux) [inline tests/expression_statement/use_strict.js]: You actually need to have this as the first expression, otherwise it is being parsed as just a string and not a directive. I would recommend making two files

File: tests/expression_statement/jsfmt.spec.js (hunk 2 above)
Comment (vjeux) [inline tests/expression_statement/jsfmt.spec.js]: Can you run the tests again, I don't see babylon on the snapshot.

File: tests/expression_statement/use_strict.js (hunk 3 above)
Comment (yamafaktory) [inline tests/expression_statement/use_strict.js]: Oh, you're right 👍

File: tests/expression_statement/__snapshots__/jsfmt.spec.js.snap [hunk 4]
```diff
@@ -0,0 +1,17 @@
...
+`;
+
+exports[`test no_regression.js 1`] = `
+"// Ensure no regression.
+\"use strict\";
+~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+// Ensure no regression.
+\"use strict\";
+"
+`;
```
Comment (vjeux) [inline tests/expression_statement/__snapshots__/jsfmt.spec.js.snap]: Why don't I see the tests running with babylon?

Comment (yamafaktory) [inline tests/expression_statement/__snapshots__/jsfmt.spec.js.snap]: Isn't it correct?
```js
run_spec(__dirname);

run_spec(__dirname, {parser: 'babylon'});
```

Comment (vjeux) [inline tests/expression_statement/__snapshots__/jsfmt.spec.js.snap]: Did you do `yarn test -- -u`?

Comment (yamafaktory) [inline tests/expression_statement/__snapshots__/jsfmt.spec.js.snap]: Just did it and got:

```shell
Test suite failed to run

Error: No message was provided
```

Comment (vjeux) [inline tests/expression_statement/__snapshots__/jsfmt.spec.js.snap]: This is really weird, I'm not really sure what's going on, it looks right :x

**Comment by vjeux** [comment]
```js
// Parentheses around expression statement should be preserved in this case.
("use strict");
```

Flow dies in agony while trying to parse the file:

```js
[ 0,
  [ 248, aw { t: 0, c: 'Failure', l: 7 }, -3 ],
  aw { t: 0, c: 'Nooo: T_LPAREN\n', l: 15 } ]
```

**Comment by yamafaktory** [comment]
@vjeux wow, ok... what should we do then? Bypassing flow and only using Babylon in this case?

**Comment by vjeux** [comment]
Yeah, let's just run babylon

**Comment by lydell** [comment]
For reference, here's the flow bug: facebook/flow#3234

**Comment by vjeux** [comment]
Oh cool, there's already a fix in. So in a couple of days when 0.39 ships it'll work :)

**Comment by vjeux** [comment]
Thanks!
