### PR TITLE
Remove trailing whitespace in broken arrow function expressions.

### LINKED ISSUE #103: Trailing whitespaces
First of all, love the project. I'm using scalafmt to format scalacode and all the debates regarding lint and codestyle and nitpicks in PRs disappeared when enabling it. Really looking forward to this taking off!

Now to the issue. It seems that arrow functions are, at least in some cases, leaving a trailing whitespace when reformatted.

I've attached two examples off git diffs where it leaves a trailing comma for me.
image
image

If additional information is needed I'll try my best to get some more context.

### PR DESCRIPTION
**Pull request by demoneaux**
Closes #103.

### CODE REVIEW

File: src/printer.js [hunk 1]
```diff
@@ -334,10 +334,10 @@ function genericPrintNoParens(path, options, print) {
       ])));
     }
 
-    parts.push(" => ");
+    parts.push(" =>");
 
     return conditionalGroup([
-      concat([ concat(parts), path.call(print, "body") ]),
+      concat([ concat(parts.concat([" "])), path.call(print, "body") ]),
```
Comment (jlongster) [inline src/printer.js]: You can just do `concat([ concat(parts), " ", path.call(print, "body") ])` which removes that `.concat` call

**Comment by demoneaux** [comment]
Updated and rebased.
