### PR TITLE
Fix windows line-endings

### LINKED ISSUE #151: prettier introduce extra line break when CRLF
e.g.

```js
const vscode = require("vscode");
const {getDir, getActiveFile, uint8arrayToString} = require("./utils");

let outChannel;
let _commands;
```

=>

```js
const vscode = require("vscode");

const {getDir, getActiveFile, uint8arrayToString} = require("./utils");

let outChannel;

let _commands;

```
It works as expected when line ending is LF.

It took me an hour to figure out the root cause.
:(

### PR DESCRIPTION
**Pull request by vjeux**
The search for an empty line incorrectly does +1 which happens to be skipping a `\n`, but in case of windows line endings it skips the `\r` but sees a `\n` afterwards and incorrectly assumes that it is a empty line.

This doesn't change the behavior of doing +1 when there's not a line ending. Making it correct actually triggers a bunch of changes, where half of them are better and half of them regressions. So I'm going to send another pull request to fix that case.

Fixes #151

### CODE REVIEW

**Comment by jwasinger** [comment]
Please ignore my pull request.  It is incorrect.

File: src/util.js [hunk 1]
```diff
@@ -234,9 +234,20 @@ util.getLast = function(arr) {
...
 
+function skipNewLineForward(text, index) {
+  if (text.charAt(index) === "\n") {
+    return index + 1;
+  }
+  if (text.charAt(index) === "\r" && text.charAt(index + 1) === "\n") {
+    return index + 2;
+  }
+  // Note: this is incorrect, but makes the current tests pass for now.
+  return index + 1;
```
Comment (jlongster) [inline src/util.js]: Interesting. I see how this is wrong and I'm curious what the effects are.

**Comment by jlongster** [comment]
Very cool, thanks for digging through this!

File: src/util.js (hunk 1 above)
Comment (vjeux) [inline src/util.js]: If you merge this one, I can send the follow up that changes this :)
