### PR TITLE
JSX whitespace fixes

### LINKED ISSUE #614: Spurious empty line in JSX
```js
x = (
  <div>
    <span
      className="nuclide-console-new-messages-notification-icon icon icon-nuclicon-arrow-down"
    />
    New Messages
  </div>
);
```

turns into

```js
x = (
  <div>
    <span
      className="nuclide-console-new-messages-notification-icon icon icon-nuclicon-arrow-down"
    />

    New Messages
  </div>
);
```

with an empty line before "New Messages".

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22x%20%3D%20(%5Cn%20%20%3Cdiv%3E%5Cn%20%20%20%20%3Cspan%5Cn%20%20%20%20%20%20className%3D%5C%22nuclide-console-new-messages-notification-icon%20icon%20icon-nuclicon-arrow-down%5C%22%5Cn%20%20%20%20%2F%3E%5Cn%20%20%20%20New%20Messages%5Cn%20%20%3C%2Fdiv%3E%5Cn)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

cc @rattrayalex

### LINKED ISSUE #622: JSX spaces are not stable
```js
sortIndicator =
  <span> <Icon icon={sortDescending ? 'triangle-down' : 'triangle-upward'} /></span>;
```

turns into

```js
sortIndicator = (
  <span>
     <Icon icon={sortDescending ? 'triangle-down' : 'triangle-upward'} />
  </span>
);
```

which then turns into

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22sortIndicator%20%3D%5Cn%20%20%3Cspan%3E%20%3CIcon%20icon%3D%7BsortDescending%20%3F%20'triangle-down'%20%3A%20'triangle-upward'%7D%20%2F%3E%3C%2Fspan%3E%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3Atrue%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

```js
sortIndicator = (
  <span>
    <Icon icon={sortDescending ? 'triangle-down' : 'triangle-upward'} />
  </span>
);
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22sortIndicator%20%3D%20(%5Cn%20%20%3Cspan%3E%5Cn%20%20%20%20%20%3CIcon%20icon%3D%7BsortDescending%20%3F%20'triangle-down'%20%3A%20'triangle-upward'%7D%20%2F%3E%5Cn%20%20%3C%2Fspan%3E%5Cn)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3Atrue%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

If you look closely, there was 3 spaces before `<Icon` and when reprinted, there's only 2.

### PR DESCRIPTION
**Pull request by rattrayalex**
Fixes #622 

Previously also contained https://github.com/jlongster/prettier/pull/628 and https://github.com/jlongster/prettier/pull/629

### CODE REVIEW

File: src/printer.js [hunk 1]
```diff
@@ -2401,45 +2407,44 @@ function printJSXElement(path, options, print) {
...
-      forcedBreak = true;
+  let groups = [[]]; // Initialize the first line's group
+  children.forEach((child, i) => {
+    // leading and trailing JSX whitespace don't go into a group
+    if (i === 0 && isJSXWhitespace(child)) {
+      groups.unshift(child);
+      return;
+    } else if (i === children.length - 1 && isJSXWhitespace(child)) {
+      groups.push(child);
+      return;
```
Comment (rattrayalex) [inline src/printer.js]: this block of code (immediately above this) is the meat of this diff; the other changes are just because the `if (children.length === 1) {` is no longer required.

File: tests/flow/more_react/__snapshots__/jsfmt.spec.js.snap [hunk 2]
```diff
@@ -126,7 +126,7 @@ var App = require(\"App.react\");
 
 var app = (
   <App y={42}>
-     // error, y: number but foo expects string in App.react
+    {\" \"}// error, y: number but foo expects string in App.react
```
Comment (rattrayalex) [inline tests/flow/more_react/__snapshots__/jsfmt.spec.js.snap]: this highlights that this "comment" was never actually a comment. not problematic, just confusing.

File: src/printer.js [hunk 3]
```diff
@@ -2401,45 +2407,44 @@ function printJSXElement(path, options, print) {
...
+  });
+
+  const childrenGroupedByLine = [
+    hardline,
+    // Conditional groups suppress break propagation; we want to output
+    // hard lines without breaking up the entire jsx element.
+    concat(groups.map(contents =>
+      Array.isArray(contents)
+        ? conditionalGroup([concat(contents)])
+        : contents
```
Comment (rattrayalex) [inline src/printer.js]: this is the other substantive part of the change, which I feel a little meh about.

**Comment by vjeux** [comment]
<3

I think it would be easier to review to make 3 prs since you already have the commits split up. Anyway, I'll let @jlongster review it since he did the rest.

Great job, thanks for fixing all those so quickly

File: tests/jsx-significant-space/__snapshots__/jsfmt.spec.js.snap [hunk 4]
```diff
@@ -113,5 +128,37 @@ nest_plz = (
...
+  </span>
+);
+
+regression_not_transformed_2 = (
+  <span>
+    <Icon icon=\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\" />{\" \"}
+  </span>
+);
+
+similar_1 = (
```
Comment (rattrayalex) [inline tests/jsx-significant-space/__snapshots__/jsfmt.spec.js.snap]: similar_1, similar_2, and similar_3 aren't necessary to verify the current implementation, but might be handy later. thoughts on over-testing?

**Comment by rattrayalex** [comment]
Heh, cool, will do

**Comment by rattrayalex** [comment]
Split out fix for #614 into #628 
and fix for #619 into #629

File: src/printer.js [hunk 5]
```diff
@@ -2256,6 +2256,12 @@ function isEmptyJSXElement(node) {
   }
 }
 
+function isJSXWhitespace(node) {
```
Comment (rattrayalex) [inline src/printer.js]: kind of iffy on this, would be preferable to have one `jsxWhitespace` object, set once, that could be compared `===`. Couldn't think of a quick way to do so, figured this approach was fine.

File: src/printer.js [hunk 6]
```diff
@@ -2256,6 +2256,12 @@ function isEmptyJSXElement(node) {
...
+  if (node.type !== "if-break") return false;
+  if (node.flatContents !== " ") return false;
+  return (node.breakContents ===  '{" "}' || node.breakContents === "{' '}");
```
Comment (jlongster) [inline src/printer.js]: We really shouldn't be accessing the internal properties of the printer nodes. If you're looking to do `doc === jsxWhitespace`, you can create the `jsxWhitespace` doc in `printJSXElement` and pass it into `printJSXChildren`.

File: tests/jsx-significant-space/__snapshots__/jsfmt.spec.js.snap (hunk 4 above)
Comment (jlongster) [inline tests/jsx-significant-space/__snapshots__/jsfmt.spec.js.snap]: Snapshot tests are so cheap that it's totally fine! :)

File: src/printer.js (hunk 3 above)
Comment (jlongster) [inline src/printer.js]: I don't fully understand all this code, but if it works, it's fine to me. I don't see anything alarming. Thanks!

File: src/printer.js (hunk 6 above)
Comment (rattrayalex) [inline src/printer.js]: Cool that sounds good to me. Thanks!

File: src/printer.js (hunk 3 above)
Comment (rattrayalex) [inline src/printer.js]: 😕 yeah, I spent a little while trying to make it more clear and gave up. Added a comment or two in the latest version though, hopefully that helps.

Comment (jlongster) [inline src/printer.js]: It does, thanks! The code itself looks good, but it just takes a while to get all the context for the JSX code, and I'm trying to quickly go through all the many PRs :)

Thanks for fixing!

**Comment by jlongster** [comment]
Thanks for responding so quickly! Merging.

**Comment by rattrayalex** [comment]
Awesome, thanks for a quick and helpful review!
