### PR TITLE
Fix trailing new lines preservation

### LINKED ISSUE #723: Last line comment is not stable
```js
function f() {
  a
  /* eslint-disable */
}
```

turns into

```js
function f() {
  a;

  /* eslint-disable */
}
```

and back

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22function%20f()%20%7B%5Cn%20%20a%5Cn%20%20%2F*%20eslint-disable%20*%2F%5Cn%7D%5Cn%5Cnfunction%20f()%20%7B%5Cn%20%20a%3B%5Cn%5Cn%20%20%2F*%20eslint-disable%20*%2F%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

Originally reported by @alekhurst in #717

### PR DESCRIPTION
**Pull request by vjeux**
There is an off by one error which made the algorithm not work all the time. In many cases, it actually is the opposite, so whenever you save, it adds/removes that line. I noticed it during the --debug-check run on our codebase but didn't investigate.

Fixes #723

### CODE REVIEW

File: src/util.js [hunk 1]
```diff
@@ -200,7 +200,9 @@ function isPreviousLineEmpty(text, node) {
   let idx = locStart(node) - 1;
   idx = skipSpaces(text, idx, { backwards: true });
   idx = skipNewline(text, idx, { backwards: true });
-  return hasNewline(text, idx, { backwards: true });
```
Comment (vjeux) [inline src/util.js]: The issue is that `hasNewLine` does `opts.backwards ? index - 1 : index` so it skips one character. We need to skip that character when you are the first caller (see `-1` 3 lines above) but we don't want to do it for intermediate processing. Since `hasNewLine` is also exported it needs to do that.

This isn't a really great situation but I don't expect this part of the codebase to change that much in the future so it's good for now.

This PR inlines the implementation of hasNewLine.

File: tests/comments/__snapshots__/jsfmt.spec.js.snap [hunk 2]
```diff
@@ -862,20 +847,43 @@ exports[`test preserve-new-line-last.js 1`] = `
...
+  /* eslint-disable */
+}
+
 function name() {
   // comment1
   func1();
 
   // comment2
   func2();
+
```
Comment (vjeux) [inline tests/comments/__snapshots__/jsfmt.spec.js.snap]: I really fucked up on that first pull request. The test I added wasn't even working -_-

File: tests/flow/covariance/__snapshots__/jsfmt.spec.js.snap [hunk 3]
```diff
@@ -65,6 +65,7 @@ var nv: NVerbose<number, *> = new NVerbose();
 nv.x = [0];
 (nv.x[0]: string); // error
 (nv.foo()[0]: string); // error
+
```
Comment (vjeux) [inline tests/flow/covariance/__snapshots__/jsfmt.spec.js.snap]: This is correct

File: tests/flow/while/__snapshots__/jsfmt.spec.js.snap [hunk 4]
```diff
@@ -30,7 +30,6 @@ function foo(x: boolean) {
     }
     return;
   }
-
```
Comment (vjeux) [inline tests/flow/while/__snapshots__/jsfmt.spec.js.snap]: This is correct, it wasn't there

**Comment by jlongster** [comment]
Good catch!
